# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170818_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=14400, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
